### ISSUE TITLE
MFA and/or device registration

### ISSUE THREAD

**Issue by whaleva** [davidjrh/dnn.azureadprovider#5]
Azure AD Provider has worked well for us for over a year now.   We have stumbled lately when trying to enforce conditional access off network using MFA and/or device registration.  

In DNN we receive the generic “A critical error has occurred.” on client side, and event log we see a Page Load Exception with the following details:
InnerMessage:
There was an error processing the credentials. Contact your system administrator.
InnerStackTrace:
at DotNetNuke.Authentication.Azure.Components.AzureClient.GetToken(String responseText)
at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.ExchangeCodeForToken()
at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.AuthorizeV2()
at DotNetNuke.Services.Authentication.OAuth.OAuthClientBase.Authorize()
at DotNetNuke.Authentication.Azure.Login.OnInit(EventArgs e)
at System.Web.UI.Control.InitRecursive(Control namingContainer)
at System.Web.UI.Control.AddedControl(Control control, Int32 index)
at System.Web.UI.ControlCollection.Add(Control child)
at DotNetNuke.Modules.Admin.Authentication.Login.BindOAuthControls()
at DotNetNuke.Modules.Admin.Authentication.Login.BindLogin()
at DotNetNuke.Modules.Admin.Authentication.Login.ShowPanel()
at DotNetNuke.Modules.Admin.Authentication.Login.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

These are the versions we are currently running:
1.	Evoq Content 8.5
2.	DNN Azure Active Directory Authorization Provider Version 01.00.05

**Comment by davidjrh** [comment]
We have been successfully using the MFA features on Azure AD with this provider for a long time now. Closing this issue as old one.
